// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnoKNLcJYpB35lK57cKxXBtBOqyEaJWg',
    appId: '1:466412328498:web:c90cf2284f528fdd0c0e2b',
    messagingSenderId: '466412328498',
    projectId: 'valet-14501',
    authDomain: 'valet-14501.firebaseapp.com',
    storageBucket: 'valet-14501.appspot.com',
    measurementId: 'G-PS4YXY91X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTIts4ktuPoK97QDDPNU0twbCu3iZXcqI',
    appId: '1:466412328498:android:0cfe595388fd68d90c0e2b',
    messagingSenderId: '466412328498',
    projectId: 'valet-14501',
    storageBucket: 'valet-14501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzWWyCGNqEYNzbgnj7aTQW_9W3NKDqqbA',
    appId: '1:466412328498:ios:d677146f7abc6ec00c0e2b',
    messagingSenderId: '466412328498',
    projectId: 'valet-14501',
    storageBucket: 'valet-14501.appspot.com',
    iosClientId: '466412328498-objre894ra8f0m1m2ns36or8t62o0or2.apps.googleusercontent.com',
    iosBundleId: 'com.example.valet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzWWyCGNqEYNzbgnj7aTQW_9W3NKDqqbA',
    appId: '1:466412328498:ios:d677146f7abc6ec00c0e2b',
    messagingSenderId: '466412328498',
    projectId: 'valet-14501',
    storageBucket: 'valet-14501.appspot.com',
    iosClientId: '466412328498-objre894ra8f0m1m2ns36or8t62o0or2.apps.googleusercontent.com',
    iosBundleId: 'com.example.valet',
  );
}
